CREATE TABLE COUNTRY(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	COUNTRY_NAME VARCHAR(255) NOT NULL,
	COUNTRY_CODE VARCHAR(255) NOT NULL,
	PHONE_CODE VARCHAR(50) NOT NULL
);

CREATE TABLE AIRPORT(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	IATA_CODE VARCHAR(255) NOT NULL,
	AIRPORT_NAME VARCHAR(255) NOT NULL,
	AIRPORT_CITY VARCHAR(255) NOT NULL,
	COUNTRY_ID BIGINT NOT NULL,
	FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
);

CREATE TABLE AIRCRAFT(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	TAIL_NUMBER VARCHAR(255) NOT NULL,
	AIRCRAFT_MANUFACTURER VARCHAR(255) NOT NULL,
	AIRCRAFT_MODEL VARCHAR(255) NOT NULL,
	DATE_OF_MANUFACTURE DATETIME NOT NULL,
	PLANE_ECONOMY_CAPACITY INT NOT NULL,
	PLANE_BUSINESS_CAPACITY INT NOT NULL
);

CREATE TABLE AVAILABLE_ROUTES(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	AIRPORT1 BIGINT NOT NULL,
	AIRPORT2 BIGINT NOT NULL,
	FOREIGN KEY (AIRPORT1) REFERENCES AIRPORT (ID),
	FOREIGN KEY (AIRPORT2) REFERENCES AIRPORT (ID)
);

CREATE TABLE FLIGHT(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	FLIGHT_NUMBER VARCHAR(255) NOT NULL,
	FLIGHT_TIME_BY_MINUTES INT NOT NULL,
	GATE_NO VARCHAR(255) NOT NULL,
	FLIGHT_TYPE VARCHAR(10) NOT NULL,
	FLIGHT_ECONOMY_CAPACITY INT NOT NULL,
	FLIGHT_BUSINESS_CAPACITY INT NOT NULL,
	DEPARTURE_TIME DATETIME NOT NULL,
	AIRCRAFT_ID BIGINT NOT NULL,
	AVAILABLE_ROUTES_ID BIGINT NOT NULL,
	FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFT(ID),
	FOREIGN KEY (AVAILABLE_ROUTES_ID) REFERENCES AVAILABLE_ROUTES(ID)
);


CREATE TABLE PASSENGER (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	FIRST_LAST_NAME VARCHAR(255) NOT NULL,
	PASSPORT_NUMBER VARCHAR(255) NOT NULL,
	GENDER VARCHAR(255) NOT NULL,
	AGE VARCHAR(255) NOT NULL,
	PHONE_NUMBER VARCHAR(255) NOT NULL,
	EMAIL_ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE USER_TYPE(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	TYPE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORITY (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	USER_TYPE_ID BIGINT NOT NULL,
	AUTHORITY_NAME VARCHAR(255) NOT NULL,
	FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPE(ID)
);

CREATE TABLE BASE_USER (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	USER_NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	USER_TYPE_ID BIGINT NOT NULL,
	FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPE(ID)
);

CREATE TABLE TICKET (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CREATION_DATE DATETIME,
	UPDATE_DATE DATETIME,
	PASSENGER_SEAT VARCHAR(255) NOT NULL,
	FLIGHT_CLASS VARCHAR(255) NOT NULL,
	FLIGHT_ID BIGINT NOT NULL,
	PASSENGER_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID),
	FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID),
	FOREIGN KEY (USER_ID) REFERENCES BASE_USER(ID)
);