SET IDENTITY_INSERT User_Type ON;

INSERT INTO User_Type(ID,Creation_Date,Update_Date,Type_Name)
VALUES(1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'CUSTOMER');

INSERT INTO User_Type(ID,Creation_Date,Update_Date,Type_Name)
VALUES(2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ADMIN');

SET IDENTITY_INSERT User_Type OFF;